Sprint 17
vadamask/Tracker pull request #4
Opened 2023-10-17 21:09 UTC by vadamask

2023-10-18 20:07 UTC, protos17 requested changes

2023-10-18 20:07 UTC, protos17 commented on Tracker/Modules/StatisticsScreen/StatisticViewModel.swift
> +    @objc func updateView() {
Рекомендую указать как private

2023-10-18 20:07 UTC, protos17 commented on Tracker/Modules/StatisticsScreen/StatisticViewModel.swift
> +            print(error.localizedDescription)
Рекомеендую добавить еще один @Observable для ошибок и эту ошибку передать ему, а во вью-контроллере слушать, не пришли ли ошибки и отображать в алерте их

2023-10-18 20:07 UTC, protos17 commented on Tracker/Modules/StatisticsScreen/StatisticsViewController.swift
> +            [self?.bestPeriodView, self?.perfectDaysView, self?.trackersCompletedView, self?.avgValueView]
Если в замыкании используется много self, рекомендую сразу сделать проверку guard let self { ... и так будет работать проще

2023-10-18 20:07 UTC, protos17 commented on Tracker/Modules/TrackerSetupScreen/TrackerSetup/TrackerSetupModel.swift
> +                print(error.localizedDescription)
Рекомендую показать ошибку в алерте

2023-10-18 20:07 UTC, protos17 commented on Tracker/Modules/TrackersCollectionScreen/TrackersCollectionModel.swift
> +    let recordStore = TrackerRecordStore()
Рекомендую указать как private

2023-10-18 20:07 UTC, protos17 commented on Tracker/Modules/TrackersCollectionScreen/TrackersCollectionModel.swift
> +            print(error.localizedDescription)
Рекомендую показать ошибку здесь и ниже, где ловятся ошибки

2023-10-18 20:07 UTC, protos17 commented on TrackerTests/__Snapshots__/TrackerTests/testCollectionVCDark.1.png
Рекомендую удалить скриншоты

2023-10-19 05:52 UTC, vadamask commented on Tracker/Modules/TrackersCollectionScreen/TrackersCollectionViewController.swift
> +        navigationItem.searchController = searchController
Не знаю где спросить, напишу тут. 
Делал по туториалу kodeco. Почему там было указано, чтобы не ставить галочку?

![image](https://github.com/vadamask/Tracker/assets/53489821/174e41b5-6c9b-44c4-b220-136d3d92073e)

2023-10-19 20:21 UTC, vadamask commented
Не совсем понятно со свифтгеном. Мозги все запудрил. 

1. Пустые папки (Generated например) гит не дает коммитить, так как в курсе сказали не коммитить сгенерированные файлы.  Соответственно этот способ не подходит. 

2. Если я меняю путь сохранения на Resources (там файлы есть) и при этом добавляю в гитигнор сгенерированные файлы, то при пуше в гит и последующем скачивании проекта первый билд всегда фейлится, типа не находит этих самых файлов, но со второго раза норм. Это нормально?

3. В итоге я сделал пустые сгенерированые файлы и закоммитил их. Так всё билдится с первого раза. Но форк на каждый билд теперь видит изменения этих файлов  

Не подскажешь как вообще правильно? 🤯

2023-10-19 20:52 UTC, protos17 commented
Должно билдиться со второго раза, потому что при первом билде он как раз эти файлы создает

2023-10-20 03:48 UTC, vadamask commented
Ладно, не буду уже переделывать, чтобы историю не засорять. Запомню  на будущее.

2023-10-20 12:30 UTC, protos17 approved these changes

2023-10-20 12:30 UTC, protos17 commented on Tracker/Modules/CategoriesScreen/CategoriesListViewModel.swift
> +            name: Notification.Name.categoryChanged,
Для простоты можно просто сразу через точку вызывать:

.categoryChanged

2023-10-20 12:30 UTC, protos17 commented on Tracker/Modules/CategoriesScreen/CategoriesListViewModel.swift
> +    func deleteCategory(at indexPath: IndexPath) {
Публичные методы принято писать перед приватными

2023-10-20 12:30 UTC, protos17 commented on Tracker/Services/AnalyticsService.swift
> +    enum Item: String {
Рекомендую внести их из области видимости класса - упростится написание

2023-10-20 17:23 UTC, merged